% This is an autogenerated sample test for file all
classdef testall < matlab.unittest.TestCase
    methods (Test)
        function test_all(testCase)
            % Specify the input(s) of all
            sObj = SimulationModel;
            simulate(sObj);
            %isa(sObj.SimData, 'SimData')

            % Exercise the function all
            output2 = all(ismember(sObj.SimData.DataNames,["Drug","Receptor","Complex","RO"]));

            % Specify the expected output(s) of all
            testCase.verifyClass(sObj.SimData,'SimData');
            testCase.verifyTrue(output2);
        end
    end
end